#!/bin/bash

_get_ziplink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $FUSSION_REPO == "goodcat" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    elif [[ $FUSSION_REPO == "badcat" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2ppc2FuMDkvY2F0dXNlcmJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $FUSSION_REPO =~ $regex ]]
    then
        if [[ $FUSSION_REPO_BRANCH ]]
        then
            echo "${FUSSION_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${FUSSION_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}

_get_repolink () {
    local regex
    local rlink
    regex='(https?)://github.com/.+/.+'
    if [[ $FUSSION_REPO == "goodcat" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d`
    elif [[ $FUSSION_REPO == "badcat" ]]
    then
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL0ppc2FuMDkvY2F0dXNlcmJvdA==" | base64 -d`
    elif [[ $FUSSION_REPO =~ $regex ]]
    then
        rlink=`echo "${FUSSION_REPO}"`
    else
        rlink=`echo "aHR0cHM6Ly9naXRodWIuY29tL3NhbmR5MTcwOS9jYXR1c2VyYm90" | base64 -d`
    fi
    echo "$rlink"
}


_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_catpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_FUSSION_REPO = "https://github.com/TeamFussion/Fussion"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_FUSSION_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_cat_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_FUSSION_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$FUSSION_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_FUSSION_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath
    zippath="fussion.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_ziplink) -O "$zippath"
    echo "  Unpacking Data ..."
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    _run_catpack_git
    cd $CATPATH
    _run_cat_git
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    Starting CatUserBot    "
    echo "
                        :'######:::::'###::::'########::::
                        '##... ##:::'## ##:::... ##..:::::
                         ##:::..:::'##:. ##::::: ##:::::::
                         ##:::::::'##:::. ##:::: ##:::::::
                         ##::::::: #########:::: ##:::::::
                         ##::: ##: ##.... ##:::: ##:::::::
                        . ######:: ##:::: ##:::: ##:::::::
                        :......:::..:::::..:::::..::::::::
    "

    echo "
    '##::::'##::'######::'########:'########::'########:::'#######::'########:
     ##:::: ##:'##... ##: ##.....:: ##.... ##: ##.... ##:'##.... ##:... ##..::
     ##:::: ##: ##:::..:: ##::::::: ##:::: ##: ##:::: ##: ##:::: ##:::: ##::::
     ##:::: ##:. ######:: ######::: ########:: ########:: ##:::: ##:::: ##::::
     ##:::: ##::..... ##: ##...:::: ##.. ##::: ##.... ##: ##:::: ##:::: ##::::
     ##:::: ##:'##::: ##: ##::::::: ##::. ##:: ##:::: ##: ##:::: ##:::: ##::::
    . #######::. ######:: ########: ##:::. ##: ########::. #######::::: ##::::
    :.......::::......:::........::..:::::..::........::::.......::::::..:::::
    "
    python3 -m userbot
}

_set_bot
